### ISSUE TITLE
Bluetooth communication 

### ISSUE THREAD

**Issue by ahmdrz** [hadidimad/soccer_Simulate#1]
Can you connect to a Bluetooth device and receive data then show robot position ?

**Comment by hadidimad** [comment]
Yes we can for more information see this link

https://drive.google.com/drive/mobile/folders/0B098RnWKEU5lZkpSZWs3VkU3Y2c/0B098RnWKEU5lTVo3bVNZM0ZPTFU?sort=13&direction=a

and this one

https://forum.yoyogames.com/index.php?threads/bluetooth-for-multiplayer-games-arduino-and-other-microcontrollers.1140/

**Comment by ahmdrz** [comment]
Change your codes.
